### ISSUE TITLE
Recopilación de pruebas por hacer

### ISSUE THREAD

**Issue by ManuLG** [dpeite/JustTelemetry#92]
- [x] Trazada usando sólo el acelerómetro ( #90)
- [x] Trazada usando sólo el GPS (realizada ya en múltiples ocasiones)
- [x] Recopilación de datos de los sensores para comprobar que el simulador funciona ( #77)
- [x] Recopilación de datos de los sensores en un circuito con checkpoints conocidos (#77)
- [x] Probar la [nueva idea](https://github.com/dpeite/JustTelemetry/issues/78#issuecomment-291827382) sobre la corrección de los ejes del acelerómetro (#78)
